language: java
# Enable container-based infrastructure
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# manage the caches here https://travis-ci.org/hawkular/hawkular/caches
cache:
  directories:
  - $HOME/.m2/repository
jdk:
- oraclejdk8
install:
- mvn -s .travis.maven.settings.xml -version -B
- df -h
- du -sh $HOME/.m2/repository
script:
- PROJECT_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['`
- if [[ "${PROJECT_VERSION}" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
   echo "Building with deployment" ;
   mvn -fae -s .travis.maven.settings.xml -Pitest clean deploy -DdeployAtEnd=true ;
  else
   echo "Building without deployment" ;
   mvn -fae -s .travis.maven.settings.xml -Pitest clean install ;
  fi
- df -h
- du -sh $HOME/.m2/repository
notifications:
  email: false
env:
  global:
  - secure: h2UBs+L83eGd8+vTvd4B5sh+ixjp67JB/5Ko/zGAEt6a3hIgrhqyjiXJmaEH3+jzJZKXUcUC6uOuxXHwZ4ODeF+McHViOjqqUGEynJ7AsLXqSr5SSBKZuY/pb69phQnh7Br5w2D+5IFHWEcjrSo/kHDbeZBVAMFRDeGVwpHy2yA=
  - secure: BADgz+otMMO+gUlFNduU/mgFm1dOfv2ZWAYD3nO1nEwu7Y1QVUsqimHdlqntUcinILDVeD33oT27kElERvr7KyjfDEPSDAVUg5Y/5soezg/tBu0zi3iodAP2GynOMohS/Rfm4+3ajWuEe/Y2SYjFXgldMR9qjP+/31FsVtW8Op0=
  - secure: "BiNdt5chVhT3StF2MK/z8nB/jAM/5feOMEAeY0bmhcQQUwzxrOb8G3G26rDBPL1FApCHOP1yjyCgxruboRik4ZmweXnelBV4q1K2m6hSV8GSNQvcVhlozA6KYt9CMFOIZo5WPpXBp6Kg7ftsMft2qxzyJRYjPqPhtOct8MNDMgY="
  - secure: "IGipdqGmyhPBgXLjQ5sbWVIMbDpQvFUzuGsdoAPyeJbSNma1LFuJta6OQvueJhDoBPzAYQ/54NFW0WTrd1z3dtZjxo24/ZRvIy6TRPJRcpUSQMa+C9FwCmFb3LPsYF2NNdUKkW33610puI8iSJkt+MfCV9j5SAJc37+Cd2cXUoU="
before_cache:
# keep the cached local repo small by removing files older than 10 days
- find $HOME/.m2/repository -type d -ctime +10 -exec rm -rf {} \;
- df -h
- du -sh $HOME/.m2/repository
after_success:
- PROJECT_VERSION=`mvn --batch-mode org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['`
- if [[ "${PROJECT_VERSION}" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
   curl -X GET http://${DEPLOYMENT_JENKINS}/job/Build-Hawkular-Image/build?token=${DEPLOYMENT_JENKINS_TOKEN} ;
  fi
